connect option for loading all error codes
prusa3d/Prusa-Error-Codes pull request #134
Opened 2024-03-05 11:49 UTC by sarkafa

2024-03-05 13:33 UTC, ondratu requested changes

2024-03-05 13:33 UTC, ondratu commented on prusaerrors/shared/codes.py
MK39

2024-03-06 13:31 UTC, ondratu approved these changes

2024-03-06 13:46 UTC, sarkafa commented on prusaerrors/connect/codes.py
> +BUDDY = ['MINI', 'MK4', 'IX', 'XL', 'MK35']
added

2024-03-06 13:46 UTC, sarkafa commented on prusaerrors/shared/codes.py
added

2024-03-07 08:21 UTC, filipkotoucek approved these changes

2024-03-07 13:02 UTC, merged