SL1: add wizard error codes
prusa3d/Prusa-Error-Codes pull request #8
Opened 2020-08-20 19:27 UTC by vladamatena

Add SL1 wizard error codes. MOre wizard codes ar going to come once
uvcalibration is included.

2020-08-24 16:11 UTC, filipkotoucek requested changes

2020-08-24 16:11 UTC, filipkotoucek commented on prusaerrors/sl1/codes.py
>      EXPOSURE_TILT_FAILURE = Code(PRINTER, Category.MECHANICAL, 10, None, False)
Musime rozlisovat kde k chybe nastalo? Osobne by se mi libilo vsechny chyby mit jakoby GENERAL a nerozlisoval jestli chyba nastala v EXPOSURE nebo jinde, tedy GENERAL. Radeji bych na zacatek pridal prefix o jakou kategorii hlasky jde. ERROR bych  mozna vynechal (nejsem si jisty), protoze tech bude nejvice. Tzn prozatim by nam zbylo prefixovat WARNING, EXCEPTION.

Nemuzeme taky vyhodit slovo FAILED, aby byly identifikatory co nejkratsi?

TILT
TILT_HOME
TILT_AXIS_CHECK
TILT_ENDSTOP_NOT_REACHED
TILT_ALIGN_POSITION
DISPLAY_TEST
TEMP_AMBIENT
WRN_TEMP_AMBIENT
TEMP_UVLED - fatalni chyba prehrivani uv led
WRN_TEMP_UVLED - tiskarna se prehriva nefatalni
EXC_MOTION_CONTROLLER
MOTION_CONTROLLER_WRONG_REVISION
UV_NOT_CALIBRATED

Nebo muzeme errory nechat bez predpony, protoze jich bude asi nejvic a prexifovat pouze jine druhy hlasek?

co sloucit TILT_HOME_CHECK_FAILED,  GENERAL_TILT_HOME_FAILURE a jim podobne?

Cim mene erroru bude tim lip. Samozrejme jsou asi pripady kdy chces zobrazit jinou hlasku u velmi podobneho problemu, ale tomu bych se rad vyhnul. Pokud budes reportovat, ze ti selhali vetraky pred tiskem nebo ve wizardu, tak bys mel dostat stejnou hlasku, ktera ma obecny popis pro reseni chyby.

2020-08-24 16:11 UTC, filipkotoucek commented on prusaerrors/sl1/codes.py
> +    SOUND_TES_FAILED = Code(PRINTER, Category.ELECTRICAL, 10, _("Speaker is broken"), False)
typo

2020-08-25 09:55 UTC, vladamatena commented on prusaerrors/sl1/codes.py
>      EXPOSURE_TILT_FAILURE = Code(PRINTER, Category.MECHANICAL, 10, None, False)
Prejmenovano

2020-08-26 07:07 UTC, filipkotoucek approved these changes

2020-08-26 07:07 UTC, merged